<?php
/**
 * Created by PhpStorm.
 * User: Alannguyen
 * Date: 7/13/2019
 * Time: 3:15 PM
 */

namespace Designer\CustomContact\Controller\Index;

class Post extends \Magento\Contact\Controller\Index\Post {

    public function execute()
    {
        return parent::execute(); // TODO: Change the autogenerated stub
    }

}